# Generated by Django 5.2.7 on 2025-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_message', models.TextField()),
            ],
        ),
    ]
